# Generated by Django 2.2.16 on 2020-10-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_activity', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=500)),
                ('coordinates', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'Building',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(default='', max_length=500)),
                ('coordinates', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('floor', models.IntegerField(default=0)),
                ('activity', models.CharField(default='', max_length=255)),
                ('id_building', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Building')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='SynonymRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Room')),
            ],
        ),
        migrations.CreateModel(
            name='SynonymCampus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='SynonymBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('id_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Building')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='id_campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Campus'),
        ),
    ]
