# Generated by Django 2.2.16 on 2020-10-29 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='id_building',
        ),
        migrations.RemoveField(
            model_name='synonymbuilding',
            name='id_building',
        ),
        migrations.RemoveField(
            model_name='synonymcampus',
            name='id_campus',
        ),
        migrations.RemoveField(
            model_name='synonymroom',
            name='id_room',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='SynonymBuilding',
        ),
        migrations.DeleteModel(
            name='SynonymCampus',
        ),
        migrations.DeleteModel(
            name='SynonymRoom',
        ),
    ]
